# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_internal.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'raft_internal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13raft_internal.proto\x12\rraft.internal\"G\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0c\n\x04hash\x18\x03 \x01(\t\x12\x11\n\tlog_index\x18\x04 \x01(\x05\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\xa0\x01\n\rAppendRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12(\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x17.raft.internal.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"^\n\x0e\x41ppendResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x16\n\x0e\x63onflict_index\x18\x03 \x01(\x05\x12\x15\n\rconflict_term\x18\x04 \x01(\x05\x32\xa4\x01\n\x0cRaftInternal\x12\x46\n\x0bRequestVote\x12\x1a.raft.internal.VoteRequest\x1a\x1b.raft.internal.VoteResponse\x12L\n\rAppendEntries\x12\x1c.raft.internal.AppendRequest\x1a\x1d.raft.internal.AppendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_internal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=38
  _globals['_LOGENTRY']._serialized_end=109
  _globals['_VOTEREQUEST']._serialized_start=111
  _globals['_VOTEREQUEST']._serialized_end=207
  _globals['_VOTERESPONSE']._serialized_start=209
  _globals['_VOTERESPONSE']._serialized_end=259
  _globals['_APPENDREQUEST']._serialized_start=262
  _globals['_APPENDREQUEST']._serialized_end=422
  _globals['_APPENDRESPONSE']._serialized_start=424
  _globals['_APPENDRESPONSE']._serialized_end=518
  _globals['_RAFTINTERNAL']._serialized_start=521
  _globals['_RAFTINTERNAL']._serialized_end=685
# @@protoc_insertion_point(module_scope)
