# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_client.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'raft_client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11raft_client.proto\x12\x0braft.client\"\x1e\n\x0ePublishRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"F\n\x0fPublishResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"L\n\x0f\x43onsumeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x15\n\rcommited_data\x18\x03 \x03(\t2\x9a\x01\n\rRaftClientAPI\x12H\n\x0bPublishData\x12\x1b.raft.client.PublishRequest\x1a\x1c.raft.client.PublishResponse\x12?\n\x0b\x43onsumeData\x12\x12.raft.client.Empty\x1a\x1c.raft.client.ConsumeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHREQUEST']._serialized_start=34
  _globals['_PUBLISHREQUEST']._serialized_end=64
  _globals['_PUBLISHRESPONSE']._serialized_start=66
  _globals['_PUBLISHRESPONSE']._serialized_end=136
  _globals['_EMPTY']._serialized_start=138
  _globals['_EMPTY']._serialized_end=145
  _globals['_CONSUMERESPONSE']._serialized_start=147
  _globals['_CONSUMERESPONSE']._serialized_end=223
  _globals['_RAFTCLIENTAPI']._serialized_start=226
  _globals['_RAFTCLIENTAPI']._serialized_end=380
# @@protoc_insertion_point(module_scope)
