# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"G\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0c\n\x04hash\x18\x03 \x01(\t\x12\x11\n\tlog_index\x18\x04 \x01(\x05\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x97\x01\n\rAppendRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"^\n\x0e\x41ppendResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x16\n\x0e\x63onflict_index\x18\x03 \x01(\x05\x12\x15\n\rconflict_term\x18\x04 \x01(\x05\"\x1e\n\x0ePublishRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"F\n\x0fPublishResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"L\n\x0f\x43onsumeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x15\n\rcommited_data\x18\x03 \x03(\t2\xeb\x01\n\x08RaftNode\x12\x34\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x12.raft.VoteResponse\x12:\n\rAppendEntries\x12\x13.raft.AppendRequest\x1a\x14.raft.AppendResponse\x12:\n\x0bPublishData\x12\x14.raft.PublishRequest\x1a\x15.raft.PublishResponse\x12\x31\n\x0b\x43onsumeData\x12\x0b.raft.Empty\x1a\x15.raft.ConsumeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=20
  _globals['_LOGENTRY']._serialized_end=91
  _globals['_VOTEREQUEST']._serialized_start=93
  _globals['_VOTEREQUEST']._serialized_end=189
  _globals['_VOTERESPONSE']._serialized_start=191
  _globals['_VOTERESPONSE']._serialized_end=241
  _globals['_APPENDREQUEST']._serialized_start=244
  _globals['_APPENDREQUEST']._serialized_end=395
  _globals['_APPENDRESPONSE']._serialized_start=397
  _globals['_APPENDRESPONSE']._serialized_end=491
  _globals['_PUBLISHREQUEST']._serialized_start=493
  _globals['_PUBLISHREQUEST']._serialized_end=523
  _globals['_PUBLISHRESPONSE']._serialized_start=525
  _globals['_PUBLISHRESPONSE']._serialized_end=595
  _globals['_EMPTY']._serialized_start=597
  _globals['_EMPTY']._serialized_end=604
  _globals['_CONSUMERESPONSE']._serialized_start=606
  _globals['_CONSUMERESPONSE']._serialized_end=682
  _globals['_RAFTNODE']._serialized_start=685
  _globals['_RAFTNODE']._serialized_end=920
# @@protoc_insertion_point(module_scope)
